sonar.projectKey=flavioUBU_GestionIncidencias
sonar.organization=flavioubu
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.java.binaries=target/classes

sonar.exclusions=target/**,.scannerwork/**,**/node_modules/**
sonar.coverage.exclusions=api_flask/**,.github/**,Dockerfile,api_flask/Dockerfile